databases:
  - name: portifolio_db
    plan: free
    databaseName: portifolio_db_ot89
    user: portifolio_db_ot89_user

services:
  - type: web
    plan: free
    name: portifolio_server
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd portifolio_server && python -m gunicorn portifolio_server.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portifolio_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4