# Generated by Django 5.0.4 on 2024-05-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="background_videos/")),
                ("is_main", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
