# Generated by Django 5.0.4 on 2024-05-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_backgroundvideo_delete_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundvideo",
            name="is_main",
            field=models.BooleanField(default=True),
        ),
    ]
