# Generated by Django 5.0.4 on 2024-05-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_image_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
