# Generated by Django 5.0.4 on 2024-05-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_image_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="show_on_home_page",
            field=models.BooleanField(default=False),
        ),
    ]
