# Generated by Django 5.0.4 on 2024-05-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_image_name_alter_image_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="project",
        ),
        migrations.AddField(
            model_name="project",
            name="project_images",
            field=models.ManyToManyField(to="app.image"),
        ),
    ]
