# Generated by Django 5.0.4 on 2024-05-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_image_show_on_home_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="show_on_home_page",
        ),
        migrations.RemoveField(
            model_name="service",
            name="images",
        ),
        migrations.AddField(
            model_name="service",
            name="home_page_services_section_images",
            field=models.ManyToManyField(to="app.image"),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("project_description", models.TextField()),
                ("project_images", models.ManyToManyField(to="app.image")),
            ],
        ),
    ]
