# Generated by Django 5.0.4 on 2024-05-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_image_show_on_home_page_remove_service_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="portfolio_page_service_images",
            field=models.ManyToManyField(
                related_name="portfolio_page_services", to="app.image"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="home_page_services_section_images",
            field=models.ManyToManyField(
                related_name="home_page_services", to="app.image"
            ),
        ),
    ]
