# Generated by Django 5.0.4 on 2024-05-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_visitor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="project",
            name="position",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Position"),
        ),
    ]
