# Generated by Django 5.0.4 on 2024-05-07 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_project_options_project_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.RemoveField(
            model_name="project",
            name="position",
        ),
    ]
