# Generated by Django 5.0.4 on 2024-06-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
