# Generated by Django 5.0.4 on 2024-06-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_newslettersubscriber_subscribed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
