# Generated by Django 5.0.4 on 2024-06-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_imagecollection_image_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='collections',
        ),
        migrations.DeleteModel(
            name='ImageCollection',
        ),
    ]
