# Generated by Django 5.0.4 on 2024-06-21 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_image_collections_delete_imagecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='image group', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='ImageGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.imagegroup'),
        ),
    ]
