# Generated by Django 5.0.4 on 2024-06-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_imagegroup_image_imagegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ImageGroup',
        ),
        migrations.DeleteModel(
            name='ImageGroup',
        ),
    ]
