# Generated by Django 5.0.4 on 2024-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_image_imagegroup_delete_imagegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
