# Generated by Django 5.0.4 on 2024-06-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_project_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order']},
        ),
    ]
