# Generated by Django 5.0.4 on 2024-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_project_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
