# Generated by Django 5.0.4 on 2024-06-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_service_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order']},
        ),
    ]
