# Generated by Django 5.0.4 on 2024-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_video_youtube',
            field=models.CharField(blank=True, help_text="Go to the youtube video \n right-click on the YouTube video and select 'Copy embed code'. \n Paste here", max_length=600, null=True),
        ),
    ]
