# Generated by Django 5.0.4 on 2024-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_project_project_video_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_video_youtube',
            field=models.CharField(blank=True, help_text="Go to the youtube video. and right-click on the YouTube video. then select 'Copy embed code'. \n Paste here", max_length=600, null=True),
        ),
    ]
