# Generated by Django 5.0.4 on 2024-06-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_project_project_video_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WelcomeSectionText', models.TextField()),
                ('LeftAboutUsText', models.TextField()),
                ('MiddleAboutUsQoute', models.TextField()),
                ('MiddleAboutUsText', models.TextField()),
            ],
        ),
    ]
