# Generated by Django 5.0.4 on 2024-06-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_websitetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetext',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
