# Generated by Django 5.0.4 on 2024-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_websitetext_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitetext',
            old_name='LeftAboutUsText',
            new_name='LeftAboutUsQuote',
        ),
        migrations.RenameField(
            model_name='websitetext',
            old_name='MiddleAboutUsQoute',
            new_name='MiddleAboutUsDescription',
        ),
        migrations.AddField(
            model_name='websitetext',
            name='QuoteBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
