# Generated by Django 5.0.4 on 2024-06-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_leftaboutustext_websitetext_leftaboutusquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/'),
        ),
    ]
