# Generated by Django 5.0.4 on 2024-06-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_thumbnail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='LEAVE THIS BLANK!!!!!!!!', null=True, upload_to='images/thumbnails/'),
        ),
    ]
