# Generated by Django 5.0.4 on 2024-06-24 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_image_create_thumbnail_alter_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='create_thumbnail',
        ),
    ]
