# Generated by Django 5.0.4 on 2024-07-12 03:26

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_image_create_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_editorjs', django_editorjs_fields.fields.EditorJsJSONField()),
                ('body_editorjs_text', django_editorjs_fields.fields.EditorJsTextField()),
            ],
        ),
    ]
