# Generated by Django 5.0.4 on 2024-07-12 03:35

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_editorjs_custom',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
    ]
