# Generated by Django 5.0.4 on 2024-07-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_post_body_editorjs_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_editorjs_custom',
        ),
    ]
