# Generated by Django 5.0.4 on 2024-07-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_post_body_editorjs_custom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
